# Generated by Django 4.1 on 2024-07-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerabilities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cve_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('criticality', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update_at', models.DateTimeField(auto_now=True)),
                ('description_vulnerabilitie', models.TextField(max_length=500, null=True)),
                ('solution_date', models.DateTimeField()),
                ('description_solution', models.TextField(max_length=500, null=True)),
            ],
            options={
                'ordering': ['-solution_date'],
            },
        ),
    ]
